pacemaker:
  image: wurstmeister/storm
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - pacemaker:pacemaker
supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - pacemaker:pacemaker
ui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - pacemaker:pacemaker